\documentclass[a4paper]{article}
\usepackage[]{graphicx}\usepackage[]{xcolor}
% maxwidth is the original width if it is less than linewidth
% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.686,0.059,0.569}{#1}}%
\newcommand{\hlstr}[1]{\textcolor[rgb]{0.192,0.494,0.8}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textit{#1}}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hlstd}[1]{\textcolor[rgb]{0.345,0.345,0.345}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.161,0.373,0.58}{\textbf{#1}}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.69,0.353,0.396}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.333,0.667,0.333}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{0.737,0.353,0.396}{\textbf{#1}}}%
\let\hlipl\hlkwb

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}
\newcommand{\SweaveOpts}[1]{}  % do not interfere with LaTeX
\newcommand{\SweaveInput}[1]{} % because they are not real TeX commands
\newcommand{\Sexpr}[1]{}       % will only be parsed by R




\usepackage[utf8]{inputenc}
%\usepackage[ngerman]{babel}
\usepackage{a4wide,paralist}
\usepackage{amsmath, amssymb, xfrac, amsthm}
\usepackage{dsfont}
%\usepackage[usenames,dvipsnames]{xcolor}
\usepackage{amsfonts}
\usepackage{graphicx}
\usepackage{caption}
\usepackage{subcaption}
\usepackage{framed}
\usepackage{multirow}
\usepackage{bytefield}
\usepackage{csquotes}
\usepackage[breakable, theorems, skins]{tcolorbox}
\usepackage{hyperref}
\usepackage{cancel}
\usepackage{bm}


\input{../../style/common}

\tcbset{enhanced}

\DeclareRobustCommand{\mybox}[2][gray!20]{%
	\iffalse
	\begin{tcolorbox}[   %% Adjust the following parameters at will.
		breakable,
		left=0pt,
		right=0pt,
		top=0pt,
		bottom=0pt,
		colback=#1,
		colframe=#1,
		width=\dimexpr\linewidth\relax,
		enlarge left by=0mm,
		boxsep=5pt,
		arc=0pt,outer arc=0pt,
		]
		#2
	\end{tcolorbox}
	\fi
}

\DeclareRobustCommand{\myboxshow}[2][gray!20]{%
%	\iffalse
	\begin{tcolorbox}[   %% Adjust the following parameters at will.
		breakable,
		left=0pt,
		right=0pt,
		top=0pt,
		bottom=0pt,
		colback=#1,
		colframe=#1,
		width=\dimexpr\linewidth\relax,
		enlarge left by=0mm,
		boxsep=5pt,
		arc=0pt,outer arc=0pt,
		]
		#2
	\end{tcolorbox}
%	\fi
}


%exercise numbering
\renewcommand{\theenumi}{(\alph{enumi})}
\renewcommand{\theenumii}{\roman{enumii}}
\renewcommand\labelenumi{\theenumi}


\font \sfbold=cmssbx10

\setlength{\oddsidemargin}{0cm} \setlength{\textwidth}{16cm}


\sloppy
\parindent0em
\parskip0.5em
\topmargin-2.3 cm
\textheight25cm
\textwidth17.5cm
\oddsidemargin-0.8cm
\pagestyle{empty}

\newcommand{\kopf}[1]{
\hrule
\vspace{.15cm}
\begin{minipage}{\textwidth}
%akwardly i had to put \" here to make it compile correctly
	{\sf\bf Optimization in Machine Learning \hfill Exercise sheet #1\\
	 \url{https://slds-lmu.github.io/website_optimization/} \hfill WS 2023/2024}
\end{minipage}
\vspace{.05cm}
\hrule
\vspace{1cm}}

\newcommand{\kopfic}[1]{
\hrule
\vspace{.15cm}
\begin{minipage}{\textwidth}
%akwardly i had to put \" here to make it compile correctly
	{\sf\bf Optimization in Machine Learning \hfill Live Session #1\\
	 \url{https://slds-lmu.github.io/website_optimization/} \hfill WS 2023/2024}
\end{minipage}
\vspace{.05cm}
\hrule
\vspace{1cm}}

\newcommand{\kopfsl}[1]{
\hrule
\vspace{.15cm}
\begin{minipage}{\textwidth}
%akwardly i had to put \" here to make it compile correctly
	{\sf\bf Optimization in Machine Learning \hfill Exercise sheet #1\\
	 \url{https://slds-lmu.github.io/website_optimization/} \hfill WS 2023/2024}
\end{minipage}
\vspace{.05cm}
\hrule
\vspace{1cm}}

\newenvironment{allgemein}
	{\noindent}{\vspace{1cm}}

\newcounter{aufg}
\newenvironment{aufgabe}[1]
	{\refstepcounter{aufg}\textbf{Exercise \arabic{aufg}: #1}\\ \noindent}
	{\vspace{0.5cm}}

\newcounter{loes}
\newenvironment{loesung}
	{\refstepcounter{loes}\textbf{Solution \arabic{loes}:}\\\noindent}
	{\bigskip}
	
\newenvironment{bonusaufgabe}
	{\refstepcounter{aufg}\textbf{Exercise \arabic{aufg}*\footnote{This
	is a bonus exercise.}:}\\ \noindent}
	{\vspace{0.5cm}}

\newenvironment{bonusloesung}
	{\refstepcounter{loes}\textbf{Solution \arabic{loes}*:}\\\noindent}
	{\bigskip}



\begin{document}
% !Rnw weave = knitr



\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}

\kopfsl{7}{Multivariate Optimization 2}

\aufgabe{Gradient Descent}{

\begin{enumerate}
\item 
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{library}\hlstd{(ggplot2)}

\hlstd{c1} \hlkwb{=} \hlkwd{c}\hlstd{(}\hlopt{-}\hlnum{1.1}\hlstd{,}\hlnum{1.1}\hlstd{)}
\hlstd{c2} \hlkwb{=} \hlkwd{c}\hlstd{(}\hlnum{0.8}\hlstd{,} \hlopt{-}\hlnum{0.8}\hlstd{)}

\hlstd{S2} \hlkwb{=} \hlkwd{matrix}\hlstd{(}\hlkwd{c}\hlstd{(}\hlnum{1.1}\hlstd{,} \hlopt{-}\hlnum{0.9}\hlstd{,} \hlopt{-}\hlnum{0.9}\hlstd{,} \hlnum{1.1}\hlstd{),} \hlkwc{nrow} \hlstd{=} \hlnum{2}\hlstd{)}
\hlstd{S2_inv} \hlkwb{=} \hlkwd{solve}\hlstd{(S2)}

\hlstd{rho} \hlkwb{<-} \hlkwa{function}\hlstd{(}\hlkwc{u}\hlstd{) \{}\hlkwd{ifelse}\hlstd{(}\hlkwd{abs}\hlstd{(u)} \hlopt{<} \hlnum{1}\hlstd{, (}\hlnum{1} \hlopt{-} \hlstd{u}\hlopt{^}\hlnum{2}\hlstd{)}\hlopt{^}\hlnum{2}\hlstd{,} \hlnum{0}\hlstd{)\}}

\hlstd{dist1} \hlkwb{<-} \hlkwa{function}\hlstd{(}\hlkwc{x}\hlstd{) \{}\hlkwd{sqrt}\hlstd{((x} \hlopt{-} \hlstd{c1)} \hlopt{%*%} \hlstd{(x} \hlopt{-}\hlstd{c1))\}}
\hlstd{dist2} \hlkwb{<-} \hlkwa{function}\hlstd{(}\hlkwc{x}\hlstd{) \{}\hlkwd{sqrt}\hlstd{((x} \hlopt{-} \hlstd{c2)}  \hlopt{%*%} \hlstd{S2_inv} \hlopt{%*%} \hlstd{(x} \hlopt{-} \hlstd{c2))\}}

\hlstd{f} \hlkwb{<-} \hlkwa{function}\hlstd{(}\hlkwc{x}\hlstd{) \{}\hlkwd{rho}\hlstd{(}\hlkwd{dist1}\hlstd{(x))} \hlopt{-} \hlkwd{rho}\hlstd{(}\hlkwd{dist2}\hlstd{(x))\}}

\hlstd{x} \hlkwb{=} \hlkwd{seq}\hlstd{(}\hlopt{-}\hlnum{2}\hlstd{,} \hlnum{2}\hlstd{,} \hlkwc{by}\hlstd{=}\hlnum{0.01}\hlstd{)}
\hlstd{xx} \hlkwb{=} \hlkwd{expand.grid}\hlstd{(}\hlkwc{X1} \hlstd{= x,} \hlkwc{X2} \hlstd{= x)}

\hlstd{fxx} \hlkwb{=} \hlkwd{apply}\hlstd{(xx,} \hlnum{1}\hlstd{, f)}
\hlstd{df} \hlkwb{=} \hlkwd{data.frame}\hlstd{(}\hlkwc{xx} \hlstd{= xx,} \hlkwc{fxx} \hlstd{= fxx)}

\hlstd{cont_plot} \hlkwb{=} \hlkwd{ggplot}\hlstd{()} \hlopt{+}
    \hlkwd{geom_contour_filled}\hlstd{(}\hlkwc{data} \hlstd{= df,} \hlkwd{aes}\hlstd{(}\hlkwc{x} \hlstd{= xx.X1,} \hlkwc{y} \hlstd{= xx.X2,} \hlkwc{z} \hlstd{= fxx),}
                        \hlkwc{binwidth} \hlstd{=} \hlnum{0.05}\hlstd{)} \hlopt{+}
  \hlkwd{xlab}\hlstd{(}\hlkwd{expression}\hlstd{(x[}\hlnum{1}\hlstd{]))} \hlopt{+}
  \hlkwd{ylab}\hlstd{(}\hlkwd{expression}\hlstd{(x[}\hlnum{2}\hlstd{]))}
\hlstd{cont_plot}
\end{alltt}
\end{kframe}
\includegraphics[width=0.5\linewidth]{figure/mv-plot_r_emp-1} 
\end{knitrout}
\item 
First we analyze $\rho(u)$ for $\vert u \vert <1:$
$(1-u^2)^2 = 0 \iff (1-u^2) = 0 \iff u^2 = 1 \Rightarrow \rho(u) \neq 0$ for $u^2 < 1$ and $\rho(u) = 0$ for $u^2 \geq 1$.\\
We can check this condition for both squared distances around the centers $\mathbf{c}_1, \mathbf{c}_2$: \\
\begin{enumerate}
\item $\Vert\mathbf{x} - \mathbf{c}_1\Vert_{S_1}^2 < 1 \iff \Vert\mathbf{x} - \mathbf{c}_1\Vert_2^2 < 1$ (unit circle around $\mathbf{c}_1$)
\item $\Vert\mathbf{x} - \mathbf{c}_2\Vert_{S_2}^2 = (\mathbf{x} - \mathbf{c}_2)^\top \begin{pmatrix} 1.1 & -0.9 \\ -0.9 & 1.1\end{pmatrix}^{-1} (\mathbf{x} - \mathbf{c}_2) < 1$ (ellipse around $\mathbf{c}_2$)\\
In order to find the smallest enclosing circle of the ellipse we can use the eigendecomposition of $S_2:$ 
$\det(S_2 - \lambda \mathbf{I}) = 0 \iff  \det \begin{pmatrix} 1.1 - \lambda & -0.9 \\ -0.9 & 1.1 -\lambda\end{pmatrix} = 0 \iff \lambda^2 - 2.2\lambda + 0.4 = 0 \iff \lambda_1 = 2.0, \lambda_2 = 0.2$ \\
$\Rightarrow $ Eigenvalues $\mu_1, \mu_2$ of $S_2^{-1}$ are $\mu_i = 1/\lambda_i.$ \\
With this we get \\
$\Vert\mathbf{x} - \mathbf{c}_2\Vert_{S_2}^2 < 1 \iff  (\mathbf{x} - \mathbf{c}_2)^\top \mathbf{V}^\top \begin{pmatrix} 5 & 0 \\ 0 & 0.5\end{pmatrix}\mathbf{V} (\mathbf{x} - \mathbf{c}_2) < 1$ with $\vert\det\mathbf{V}\vert = 1.$ \\
$\Rightarrow$ the circle around $\mathbf{c}_2$ with radius $\sqrt{1/0.5} = \sqrt{2}$ encloses the ellipse. \\
$\Vert\mathbf{c}_2 - \mathbf{c}_1\Vert_2 = \sqrt{2\cdot 1.9^2} \approx 2.69 > 1 + \sqrt{2} \approx 2.41 \Rightarrow$ the circles can not intersect \\
$\Rightarrow$ the unit circle around $\mathbf{c}_1$ and the ellipse around $\mathbf{c}_2$ can not intersect $\Rightarrow$ only $\rho(\Vert\mathbf{x} - \mathbf{c}_1\Vert_{S_1})$ or $\rho(\Vert\mathbf{x} - \mathbf{c}_2\Vert_{S_2})$ can be non-zero for a given $\mathbf{x} \in \R^2.$ \\
\end{enumerate}
\item Because of b) we know that we can treat $\rho(\Vert\mathbf{x} - \mathbf{c}_1\Vert_{S_1})$ and $\rho(\Vert\mathbf{x} - \mathbf{c}_2\Vert_{S_2})$ independently. Also it follows from $\rho(u) \geq 0 \; \forall u \in \R, w_1 > 0$ and $w_2 < 0$ that the global minimum must be in $\{\mathbf{x} \in \R^2 |\; \Vert\mathbf{x} - \mathbf{c}_2\Vert_{S_2}^2 < 1\}$ \\
$\frac{\partial}{\partial \mathbf{x}}\rho(\Vert\mathbf{x} - \mathbf{c}_2\Vert_{S_2}) =  2(1 - \Vert\mathbf{x} - \mathbf{c}_2\Vert_{S_2}^2)\cdot (-2) \cdot (\mathbf{x} - \mathbf{c}_2)^\top S_2^{-1} \overset{!}{=} \mathbf{0} \Rightarrow$ either $\Vert\mathbf{x} - \mathbf{c}_2\Vert_{S_2}^2 = 1$ (which is the boundary) or $\mathbf{x} = \mathbf{c}_2$. \\
Since $-\rho(1) = 0$ and $-\rho(\Vert \mathbf{c}_2 - \mathbf{c}_2 \Vert) = -1 < 0$ it follows that the global minimum must be $\mathbf{x} = \mathbf{c}_2.$
\item 
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{# we can treat the bump functions independently b)}
\hlstd{grad} \hlkwb{<-} \hlkwa{function}\hlstd{(}\hlkwc{x}\hlstd{) \{}
  \hlkwa{if}\hlstd{((x} \hlopt{-} \hlstd{c1)} \hlopt{%*%} \hlstd{(x} \hlopt{-} \hlstd{c1)} \hlopt{<} \hlnum{1}\hlstd{)\{}
    \hlkwd{return}\hlstd{(}\hlkwd{c}\hlstd{(}\hlopt{-}\hlnum{4} \hlopt{*} \hlkwd{c}\hlstd{(}\hlnum{1} \hlopt{-} \hlstd{(x} \hlopt{-} \hlstd{c1)} \hlopt{%*%} \hlstd{(x} \hlopt{-} \hlstd{c1))} \hlopt{*} \hlstd{(x} \hlopt{-} \hlstd{c1)))}
  \hlstd{\}}\hlkwa{else if}\hlstd{((x} \hlopt{-} \hlstd{c2)} \hlopt{%*%} \hlstd{S2_inv} \hlopt{%*%} \hlstd{(x} \hlopt{-} \hlstd{c2)} \hlopt{<} \hlnum{1}\hlstd{)\{}
    \hlkwd{return}\hlstd{(}\hlkwd{c}\hlstd{(}\hlnum{4} \hlopt{*} \hlkwd{c}\hlstd{(}\hlnum{1} \hlopt{-} \hlstd{(x} \hlopt{-} \hlstd{c2)} \hlopt{%*%} \hlstd{S2_inv} \hlopt{%*%}\hlstd{(x} \hlopt{-} \hlstd{c2))} \hlopt{*} \hlstd{(x} \hlopt{-} \hlstd{c2)} \hlopt{%*%} \hlstd{S2_inv))}
  \hlstd{\}}\hlkwa{else}\hlstd{\{}
    \hlkwd{return}\hlstd{(}\hlkwd{c}\hlstd{(}\hlnum{0}\hlstd{,} \hlnum{0}\hlstd{))}
  \hlstd{\}}
\hlstd{\}}

\hlstd{alpha} \hlkwb{=} \hlnum{0.15}

\hlstd{x0} \hlkwb{=} \hlkwd{c}\hlstd{(}\hlopt{-}\hlnum{0.45}\hlstd{,} \hlnum{0.5}\hlstd{)}
\hlstd{x1} \hlkwb{=} \hlstd{x0} \hlopt{-} \hlstd{alpha} \hlopt{*} \hlkwd{grad}\hlstd{(x0)}
\hlstd{x2} \hlkwb{=} \hlstd{x1} \hlopt{-} \hlstd{alpha} \hlopt{*} \hlkwd{grad}\hlstd{(x1)}

\hlkwd{print}\hlstd{(x1)}
\end{alltt}
\begin{verbatim}
## [1] -0.365175  0.421700
\end{verbatim}
\begin{alltt}
\hlkwd{print}\hlstd{(x2)}
\end{alltt}
\begin{verbatim}
## [1] -0.365175  0.421700
\end{verbatim}
\begin{alltt}
\hlkwd{print}\hlstd{(}\hlkwd{grad}\hlstd{(x1))}
\end{alltt}
\begin{verbatim}
## [1] 0 0
\end{verbatim}
\end{kframe}
\end{knitrout}
We can not make any further progress with GD since the gradient is exactly zero.
\item Start with $\mathbf{x}^{[0]} = (-0.45, 5)^\top.$ \\
Since $\Vert\mathbf{c}_1 - \mathbf{x}^{[0]}\Vert_2^2 = 0.5525 < 1$ we know that
$\nabla f(\mathbf{x}^{[0]}) = -4(1 - \Vert\mathbf{x} - \mathbf{c}_1\Vert^2_2) \cdot (\mathbf{x} - \mathbf{c}_1)^\top = (-0.5655, 0.5220).$ \\
$\mathbf{x}^{[1]} = \mathbf{x}^{[0]} - 0.15 * (-0.5655, 0.5220)^\top = (-0.3652, 0.422)^\top.$ \\
Since $\Vert\mathbf{c}_1 - \mathbf{x}^{[1]}\Vert_2^2 = 1.0001 > 1$ and $\Vert\mathbf{c}_2 - \mathbf{x}^{[1]}\Vert^2_{S_2} = 1.4323 > 1$ the gradient of $f$ is zero at $\mathbf{x}^{[1]}.$\\
$\Rightarrow \mathbf{x}{[2]} = \mathbf{x}{[1]}$

\item 

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{alpha} \hlkwb{=} \hlnum{0.15}

\hlstd{v} \hlkwb{=} \hlkwd{c}\hlstd{(}\hlnum{0.4}\hlstd{,} \hlopt{-}\hlnum{0.4}\hlstd{)}
\hlstd{phi} \hlkwb{=} \hlnum{0.5}
\hlstd{x} \hlkwb{=} \hlkwd{c}\hlstd{(}\hlopt{-}\hlnum{0.45}\hlstd{,} \hlnum{0.5}\hlstd{)}

\hlstd{xs} \hlkwb{=} \hlstd{x}
\hlkwa{for} \hlstd{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hlnum{15}\hlstd{)\{}
  \hlstd{v} \hlkwb{=} \hlstd{phi} \hlopt{*} \hlstd{v} \hlopt{-} \hlstd{alpha}\hlopt{*}\hlkwd{grad}\hlstd{(x)}
  \hlstd{x} \hlkwb{=} \hlstd{x} \hlopt{+} \hlstd{v}
  \hlstd{xs} \hlkwb{=} \hlkwd{rbind}\hlstd{(xs, x)}
\hlstd{\}}

\hlstd{cont_plot} \hlopt{+}
  \hlkwd{geom_line}\hlstd{(}\hlkwc{data} \hlstd{=} \hlkwd{as.data.frame}\hlstd{(xs),} \hlkwd{aes}\hlstd{(}\hlkwc{x}\hlstd{=V1,} \hlkwc{y}\hlstd{=V2),} \hlkwc{color}\hlstd{=}\hlstr{"red"}\hlstd{)}
\end{alltt}
\end{kframe}
\includegraphics[width=0.5\linewidth]{figure/mv-gd_mom-1} 
\end{knitrout}


\end{enumerate}

}
\end{document}
