# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mylm1_a <- function(X, y) {
    .Call(`_myml_mylm1_a`, X, y)
}

mylm1_b <- function(X, y) {
    .Call(`_myml_mylm1_b`, X, y)
}

mylm2 <- function(X, y) {
    .Call(`_myml_mylm2`, X, y)
}

mylm3_a <- function(X, y) {
    .Call(`_myml_mylm3_a`, X, y)
}

mylm3_b <- function(X, y) {
    .Call(`_myml_mylm3_b`, X, y)
}

mylm3_c <- function(X, y) {
    .Call(`_myml_mylm3_c`, X, y)
}

mylogreg_1 <- function(X, y, stepsize, max_iter = 1000L, eps = 1e-2) {
    .Call(`_myml_mylogreg_1`, X, y, stepsize, max_iter, eps)
}

compute_square_rcpp <- function(x) {
    .Call(`_myml_compute_square_rcpp`, x)
}

