Let $f: [-1,2] \rightarrow \R, x \mapsto \exp(x^3 - 2x^2)$
\begin{enumerate}
	%
	\item Compute $f'$
	\item Plot $f$ and $f'$ with \texttt{R}.
	\item Find all possible candidates $x^*$ for local maxima and minima. \\
	\textit{Hint:} $\exp$ is a strictly monotone function.
	\item Compute $f''$
	\item Determine if the candidates are local maxima, minima or neither.
	\item Find the global maximum and global minimum of $f$
	
\end{enumerate}
